Ros 336 optimize reading
analogdevicesinc/imu-ros2 pull request #16
Opened 2023-04-06 12:17 UTC by VHolonec

Make channels reading with buffer

2023-04-06 20:04 UTC, dNechita commented on src/iio_wrapper.cpp
>  IIOWrapper::~IIOWrapper()
The m_device_buffer seems left un-destroyed.
The m_channels doesn't seem to be freed anywhere.

2023-04-06 20:06 UTC, dNechita commented on src/iio_wrapper.cpp
>      iio_context_destroy(m_object_context);
It doesn't seem that m_object_context is being used anymore. Destroying it is unnecessary.

2023-04-07 09:39 UTC, rbolboac requested changes
the commit history does not look good at all... there are a lot of changes added and then deleted just to add other changes and delete those again on the same line of code....and it is really hard to perform a review and understand what is happening.
please use git interactive rebase to perform the changes to a line of code only once.
in a pull request a line of code should be modified only once in all existing commits.

another idea would be to simply squash all commits and have a single commit which adds buffer readings support

2023-04-07 09:39 UTC, rbolboac commented on src/adiimu_ros_publisher.cpp
> +                    m_message.count);
you add this here and then you remove it in another later commit... just don't add it here at all

2023-04-07 09:39 UTC, rbolboac commented on src/acceleration_ros_publisher.cpp
> +                    std::chrono::duration_cast<std::chrono::microseconds>(done-started).count());
remove log

2023-04-07 09:39 UTC, rbolboac commented on src/iio_wrapper.cpp
> +            printf("%s chn\n", iio_channel_get_id(chn));
remove printf

2023-04-07 09:39 UTC, rbolboac commented on src/iio_wrapper.cpp
> +            }
remove

2023-04-07 09:39 UTC, rbolboac commented on src/iio_wrapper.cpp
> +         printf(" device_buffer err \n");
remove printf, instead add proper error handling, return an error

2023-04-07 09:39 UTC, rbolboac commented on src/iio_wrapper.cpp
> +    float result = fvalRaw * m_fvalScaleTemp / 10.0;
why are you dividing by 10 now? nothing should've changed

2023-04-07 09:39 UTC, rbolboac commented on src/gyroscope_ros_publisher.cpp
> +        //auto started = std::chrono::high_resolution_clock::now();
remove all commented code lines

2023-04-07 09:39 UTC, rbolboac commented on src/gyroscope_ros_publisher.cpp
> +        //            std::chrono::duration_cast<std::chrono::milliseconds>(done-started).count());
remove all commented code lines

2023-04-07 09:39 UTC, rbolboac commented on src/iio_wrapper.cpp
> +        std::string uri = "ip:127.0.0.1"; // TODO: pass uri from cmd line
this is not used, remove it

2023-04-07 09:39 UTC, rbolboac commented on src/iio_wrapper.cpp
> +        //m_local_context = iio_create_context_from_uri(uri.c_str());
remove all commented code lines

2023-04-07 09:39 UTC, rbolboac commented on src/iio_wrapper.cpp
> +        //m_object_context =  iio_context_clone(m_local_context);
remove all commented code lines

2023-04-07 09:39 UTC, rbolboac commented on src/iio_wrapper.cpp
> +    }
this code does not do anything, remove it

2023-04-07 09:39 UTC, rbolboac commented on src/iio_wrapper.cpp
> +            RCLCPP_INFO(rclcpp::get_logger("iiowrapper"),"device_buffer err");
remove log, instead use proper error handling

2023-04-07 09:39 UTC, rbolboac commented on include/imu_ros2/iio_wrapper.h
> -    std::mutex m_mutex;
this should be added in the previous commit

2023-04-07 09:39 UTC, rbolboac commented on src/iio_wrapper.cpp
> +
this should be added in a previous commit

2023-04-07 09:39 UTC, rbolboac commented on src/iio_wrapper.cpp
> +    ssize_t ret =  iio_buffer_refill(m_device_buffer);
should be added in the previous commit.
you are not doing anything with ret here... it would be a good idea to return it

2023-04-07 09:39 UTC, rbolboac commented on src/iio_wrapper.cpp
> +        //m_local_context = iio_create_local_context();
you keep changing these lines through the commit... change it just once in the final form

2023-04-07 09:39 UTC, rbolboac commented on src/iio_wrapper.cpp
> +        for (int i = 0; i < m_channel_count; ++i)
this should be the only change done here...just remove the version in which you use the 7 channels

2023-04-10 11:46 UTC, rbolboac commented on src/iio_wrapper.cpp
> +                m_channel_count++;
it would be better if the variable would be called m_scan_channel_count

2023-04-10 11:46 UTC, rbolboac commented on src/iio_wrapper.cpp
> +        }
in this case a for loop is not alright, m_channel_count is the number of all channels which can be read with the buffer. so variable i should be incremented only if the channel is added to the list
the code should be changed to something like this:
```
i = 0;
while (i < m_scan_channel_count)
{
            struct iio_channel *chn = iio_device_get_channel(m_dev, i);
            if (iio_channel_is_scan_element(chn))
            {
                m_channels[i++] = chn;
            }
}
```

2023-04-10 11:46 UTC, rbolboac commented on src/iio_wrapper.cpp
> +    iio_device_set_trigger(m_dev, m_devtrigger);
need to check if API is returning successfully a throw an exception otherwise

2023-04-10 11:46 UTC, rbolboac commented on src/iio_wrapper.cpp
> +        iio_buffer_set_blocking_mode(m_device_buffer, true);
let's check if this is truly needed, I think by default the buffer is set in blocking mode

2023-04-10 11:46 UTC, rbolboac commented on src/iio_wrapper.cpp
> +        if(m_channel_count == 14)
this if is not needed

2023-04-18 08:31 UTC, rbolboac approved these changes

2023-04-18 12:37 UTC, SeptimiuVana approved these changes

2023-04-18 12:37 UTC, merged