Added parameter description
analogdevicesinc/imu-ros2 pull request #41
Opened 2023-07-24 07:38 UTC by VHolonec

2023-07-24 08:09 UTC, rbolboac requested changes
bias_correction_time_base_control description is missing, also please add minimum and maximum allowed values in the description for all parameters

2023-07-24 11:48 UTC, rbolboac commented on src/imu_control_parameters.cpp
> +  param_range_float.to_value = 2000.0;
this is already set in the switch case so can be removed

2023-07-24 11:54 UTC, rbolboac approved these changes

2023-07-24 12:14 UTC, rbolboac approved these changes

2023-07-25 06:28 UTC, rbudai98 approved these changes

2023-07-25 06:28 UTC, merged